spring.datasource.url=jdbc:postgresql://localhost:5444/accommodation-db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.orm.jdbc.bind=TRACE
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.mk.ukim.finki.wp.lab2233009.listener=DEBUG
