
spring.application.name=emc-lab-233009
spring.profiles.active=dev

# ??????? ?? ?????????? ?? Docker
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:accommodation-db}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate ???????? (??????? validate, ???????? ???? update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Flyway ? Swagger
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
springdoc.swagger-ui.path=/swagger-ui.html

# ????????
logging.level.mk.ukim.finki.wp.lab2233009.listener=DEBUG
app.stats.mv.refresh-ms=60000

# JWT ??????????
jwt.secret=${JWT_SECRET}
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer