apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: travel-app
data:
  POSTGRES_DB: "accommodation-db"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: travel-app
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "1234"
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: travel-app
spec:
  clusterIP: None
  selector:
    app: db
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: travel-app
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:17.4
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi